# Generated by Django 5.2.1 on 2025-05-14 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Silinme"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Kategori Adı")),
            ],
            options={
                "verbose_name": "Blog Kategorisi",
                "verbose_name_plural": "Blog Kategorileri",
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellenme"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Silinme"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlık")),
                ("slug", models.SlugField(unique=True)),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/", verbose_name="Görsel"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Yayında mı?"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.blogcategory",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Yazısı",
                "verbose_name_plural": "Blog Yazıları",
            },
        ),
    ]
