# Generated by Django 5.2.1 on 2025-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcategory",
            name="name_en",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Kategori Adı"
            ),
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="name_tr",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Kategori Adı"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_en",
            field=models.TextField(null=True, verbose_name="İçerik"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="content_tr",
            field=models.TextField(null=True, verbose_name="İçerik"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Başlık"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_tr",
            field=models.CharField(max_length=255, null=True, verbose_name="Başlık"),
        ),
    ]
