# Generated by Django 5.2.1 on 2025-05-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogcategory_name_en_blogcategory_name_tr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcategory",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
